# Generated by Django 4.1.5 on 2023-01-14 22:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azitemanime',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=512, null=True), default=[''], size=None),
        ),
        migrations.AddField(
            model_name='azitemmovie',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=512, null=True), default=[''], size=None),
        ),
    ]
