# Generated by Django 4.1.5 on 2023-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_trailer_link_azitemmovie_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='azitemanime',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
