# Generated by Django 4.1.5 on 2023-03-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_azsubitemanime_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azsubitemanime',
            options={'ordering': ['episode']},
        ),
    ]
